name: Unit Test

env:
  WP_FOLDER_PATH: "/tmp/wordpress"
  TOOLS_FOLDER_PATH: "~/tools"
  WP_VERSION: "latest"
  DB_NAME: "test"
  TEST_DB_NAME: "wploader"

  WP_URL: "http://wp.localhost"
  WP_DOMAIN: "wp.localhost"
  WP_TABLE_PREFIX: "wp_"
  WP_ADMIN_USERNAME: "admin"
  WP_ADMIN_PASSWORD: "admin"

on:
  push:
    branches: [ master, Dev ]
  pull_request:
    branches: [ master, Dev ]

jobs:
  tests:
    name: Test on PHP ${{ matrix.php_versions }}

    runs-on: ubuntu-16.04
    continue-on-error: ${{ matrix.php_versions == '8.1' }}

    strategy:
      matrix:
        php_versions: [ '7.4', '8.0', '8.1' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_versions }}
          coverage: xdebug2
          # extensions: gd, zip
          tools: composer:v1

      - uses: ramsey/composer-install@v1
        with:
          composer-options: "--prefer-dist --ignore-platform-reqs"

      - name: Install WP-CLI
        run: |
          mkdir ${{env.TOOLS_FOLDER_PATH}}
          # install wp-cli in the `tools` folder
          wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -P ${{env.TOOLS_FOLDER_PATH}}
          chmod +x ${{env.TOOLS_FOLDER_PATH}}/wp-cli.phar && mv ${{env.TOOLS_FOLDER_PATH}}/wp-cli.phar ${{env.TOOLS_FOLDER_PATH}}/wp
          # prepend the `tools` folder to the PATH
          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          echo ${{env.TOOLS_FOLDER_PATH}} >> $GITHUB_PATH
          # prepend the `vendor/bin` folder to the PATH
          echo "vendor/bin" >> $GITHUB_PATH

      - name: Install WordPress
        run: |
          mkdir -p ${{env.WP_FOLDER_PATH}}
          cd $WP_FOLDER_PATH
          wp core download --version=$WP_VERSION

#      - name: Folder permission for _output
#        run: ls tests

      - name: Folder permission for _output
        run: sudo chmod -R 777 tests/_output

      - name: Run test suite
        run: vendor/bin/codecept run unit --coverage-text

#      - name: Run infection suite
#        run: vendor/bin/infection --threads=4

#      - name: Run PHPBench suite
#        run: vendor/bin/phpbench run --report=performance
